services:
  api:
    build:
      context: ./api
      dockerfile: api.dockerfile
    environment:
      - PLEX_AUTH_TOKEN
      - PLEX_LOCATION
    image: plexmoviepicker-api
  client:
    build:
      context: ./client
      dockerfile: client.dockerfile
    image: plexmoviepicker-client
    ports:
      - "25002:80"
version: '3'
